export const PUBLISHER_SET = "PUBLISHER_SET";
export const PUBLISHERS_SET = "PUBLISHERS_SET";
export const PUBLISHER_DELETE = "PUBLISHER_DELETE";
export const PUBLISHERS_STATE_CLEAR = "PUBLISHERS_STATE_CLEAR";
export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";
