export const PUBLISHER_SET = "PUBLISHER_SET";
export const PUBLISHERS_SET = "PUBLISHERS_SET";
export const PUBLISHER_DELETE = "PUBLISHER_DELETE";
export const PUBLISHERS_STATE_CLEAR = "PUBLISHERS_STATE_CLEAR";

export const AUTHOR_SET = "AUTHOR_SET";
export const AUTHORS_SET = "AUTHORS_SET";
export const AUTHOR_APPEND = "AUTHOR_APPEND";
export const AUTHOR_DELETE = "AUTHOR_DELETE";
export const AUTHOR_UPDATE = "AUTHOR_UPDATE";
export const AUTHORS_STATE_CLEAR = "AUTHORS_STATE_CLEAR";

export const GENRE_SET = "GENRE_SET";
export const GENRES_SET = "GENRES_SET";
export const GENRE_APPEND = "GENRE_APPEND";
export const GENRE_DELETE = "GENRE_DELETE";
export const GENRE_UPDATE = "GENRE_UPDATE";
export const GENRES_STATE_CLEAR = "GENRES_STATE_CLEAR";
export const RESET_STATE = "RESET_STATE";

export const LANGUAGE_SET = "LANGUAGE_SET";
export const LANGUAGES_SET = "LANGUAGES_SET";
export const LANGUAGE_APPEND = "LANGUAGE_APPEND";
export const LANGUAGE_DELETE = "LANGUAGE_DELETE";
export const LANGUAGE_UPDATE = "LANGUAGE_UPDATE";
export const LANGUAGES_STATE_CLEAR = "LANGUAGES_STATE_CLEAR";

export const BOOK_SET = "BOOK_SET";
export const BOOKS_SET = "BOOKS_SET";
export const BOOK_DELETE = "BOOK_DELETE";
export const BOOK_UPDATE = "BOOK_UPDATE";
export const BOOKS_STATE_CLEAR = "BOOKS_STATE_CLEAR";

export const TOPIC_SET = "TOPIC_SET";
export const TOPICS_SET = "TOPICS_SET";
export const TOPIC_APPEND = "TOPIC_APPEND";
export const TOPIC_DELETE = "TOPIC_DELETE";
export const TOPIC_UPDATE = "TOPIC_UPDATE";
export const TOPICS_STATE_CLEAR = "TOPICS_STATE_CLEAR";

export const POST_SET = "POST_SET";
export const POSTS_SET = "POSTS_SET";
export const POST_APPEND = "POST_APPEND";
export const POST_DELETE = "POST_DELETE";
export const POST_UPDATE = "POST_UPDATE";
export const POSTS_STATE_CLEAR = "POSTS_STATE_CLEAR";

export const PAGE_SET = "PAGE_SET";
export const PAGES_SET = "PAGES_SET";
export const PAGE_APPEND = "PAGE_APPEND";
export const PAGE_DELETE = "PAGE_DELETE";
export const PAGE_UPDATE = "PAGE_UPDATE";
export const PAGES_STATE_CLEAR = "PAGES_STATE_CLEAR";

export const SLIDER_SET = "SLIDER_SET";
export const SLIDERS_SET = "SLIDERS_SET";
export const SLIDER_APPEND = "SLIDER_APPEND";
export const SLIDER_DELETE = "SLIDER_DELETE";
export const SLIDER_UPDATE = "SLIDER_UPDATE";
export const SLIDERS_STATE_CLEAR = "SLIDERS_STATE_CLEAR";

export const CONFIG_SET = "CONFIG_SET";
export const CONFIGS_SET = "CONFIGS_SET";
export const CONFIG_APPEND = "CONFIG_APPEND";
export const CONFIG_DELETE = "CONFIG_DELETE";
export const CONFIG_UPDATE = "CONFIG_UPDATE";
export const CONFIGS_STATE_CLEAR = "CONFIGS_STATE_CLEAR";

export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";
