export const PUBLISHER_SET = "PUBLISHER_SET";
export const PUBLISHERS_SET = "PUBLISHERS_SET";
export const PUBLISHER_DELETE = "PUBLISHER_DELETE";
export const PUBLISHERS_STATE_CLEAR = "PUBLISHERS_STATE_CLEAR";

export const AUTHOR_SET = "AUTHOR_SET";
export const AUTHORS_SET = "AUTHORS_SET";
export const AUTHOR_APPEND = "AUTHOR_APPEND";
export const AUTHOR_DELETE = "AUTHOR_DELETE";
export const AUTHORS_STATE_CLEAR = "AUTHORS_STATE_CLEAR";

export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";

